const ADDNEWCONTACT = "ADD_NEW_CONTACT";
const DELETECONTACT = "DELETE_NEW_CONTACT";
const SETFILTER = "FILTER_CONTACT";
const SETALERT = "ALERT_CONTACT"
const SETLOADING = "LOADING_CONTACT";
const SETERROR = "SET_ERROR";

export { ADDNEWCONTACT, DELETECONTACT, SETFILTER, SETALERT, SETLOADING, SETERROR }